version: '3.8'

services:
  # Servicio Frontend
  web01:
    build: ./web/web01
    container_name: web-localhost-01
    ports:
      - "4001:80"
    networks:
      - lab_network

  # Servicio Backend
  api01:
    build: ./api
    container_name: api-localhost-01
    ports:
      - "4002:3000"
    environment:
      - DB_HOST=db01
    depends_on:
      - db01
    networks:
      - lab_network

  # Servicio Base de Datos
  db01:
    image: postgres:latest
    container_name: db-localhost-01
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_db
    ports:
      - "4003:5432"
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge